name: Elasticsearch Behat Tests

on:
  push:
    branches:
      - develop
  pull_request:
    types:
      - opened
      - synchronize
      - please-review

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: AKIAI2VOBUYKPQFMXW6A
          aws-secret-access-key: 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
          aws-region: us-east-1

      - name: Login to AWS ECR
        id: login-ecr
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 077428399685.dkr.ecr.us-east-1.amazonaws.com


      - name: Set up Core container
        run: |
          docker run -d --name core -p 9001:9000 -e "ENV=local" -e "ELASTIC_ENV=local" -e "AUTH_ENV=local" 077428399685.dkr.ecr.us-east-1.amazonaws.com/local-hireme-core:corev4


      - name: Set up Elasticsearch container
        run: |
          docker run -d --name elasticsearch -p 9200:9200 -e "discovery.type=single-node" -e "ELASTIC_USERNAME=elastic" -e "ELASTIC_PASSWORD=changeme"  077428399685.dkr.ecr.us-east-1.amazonaws.com/local-hireme-elasticsearch:v1.0.7
          sleep 10

      - name: Set up MongoDB
        run: |
          docker run -d --name mongodb -p 27017:27017 077428399685.dkr.ecr.us-east-1.amazonaws.com/local-hireme-mongodb:v4.2.0

      - name: Check if container is running
        run: |
          check_container() {
            local container_name=$1
            if [[ ! $(docker ps -qf name=$container_name) ]]; then
              echo "The '$container_name' container is not running."
              exit 1
            else
              echo "The '$container_name' container is running."
            fi
          }

          check_container core
          check_container elasticsearch
          check_container mongodb

      - name: Install core dependencies
        run: |
          docker run --rm --volume $(pwd):/app 077428399685.dkr.ecr.us-east-1.amazonaws.com/local-hireme-composer:v1.0.5 install -o --ignore-platform-reqs

      - name: Generate Core Config
        run: |
          cp $(pwd)/config/development.config.php.dist $(pwd)/config/development.config.php |
#          docker exec core /var/www/vendor/bin/phing generate-config |
          ls -al $(pwd)/config

      - name: Restore mongodb database
        run: |
          docker exec core /var/www/vendor/bin/phing restore-db

      - name: Restore elasticsearch database
        run: |
          docker exec core /var/www/vendor/bin/phing restore-es

      - name: debug directories
        run: ls -al

      - name: Run Behat Tests
        run: echo "test is running"